---
#**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.**

In [1]:
import numpy as np

# Q1
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))
---

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


---
#**Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.**

In [2]:
# Q2
for element in list_:
    print("Data type of element in list_:", type(element))
for element in array_list:
    print("Data type of element in array_list:", type(element))
    ---

Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>


---
#**Q3. Considering the following changes in the variable, array_list:**
array_list = np.array(object = list_, dtype = int)

In [6]:
# Q3
array_list = np.array(object=list_, dtype=int)
for element in list_:
    print("Data type of element in list_ after conversion:", type(element))
for element in array_list:
    print("Data type of element in array_list after conversion:", type(element))

Data type of element in list_ after conversion: <class 'str'>
Data type of element in list_ after conversion: <class 'str'>
Data type of element in list_ after conversion: <class 'str'>
Data type of element in list_ after conversion: <class 'str'>
Data type of element in list_ after conversion: <class 'str'>
Data type of element in array_list after conversion: <class 'numpy.int64'>
Data type of element in array_list after conversion: <class 'numpy.int64'>
Data type of element in array_list after conversion: <class 'numpy.int64'>
Data type of element in array_list after conversion: <class 'numpy.int64'>
Data type of element in array_list after conversion: <class 'numpy.int64'>


---
#**Q4. Write a code to find the following characteristics of variable, num_array:**

*   (i) shape
*   (ii) size


In [7]:
# Q4
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


---
#**Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.**

In [8]:
# Q5
zeros_array = np.zeros((3, 3))
print("Array of zeros:\n", zeros_array)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---
#**Q6. Create an identity matrix of shape (5,5) using numpy functions?**

In [9]:
# Q6
identity_matrix = np.eye(5)
print("Identity matrix:\n", identity_matrix)

Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
